#############################################################################
# Makefile for building: sorry
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun May 4 20:23:54 2014
# Project:  sorry.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile sorry.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bank.cpp \
		centralwidget.cpp \
		dialog.cpp \
		dialogpieces.cpp \
		guiplayer.cpp \
		guiplayerhorizontal.cpp \
		guiplayervertical.cpp \
		guispace.cpp \
		mainwindow.cpp \
		player.cpp \
		sorry.cpp \
		space.cpp moc_centralwidget.cpp \
		moc_guiplayer.cpp \
		moc_guiplayerhorizontal.cpp \
		moc_guiplayervertical.cpp \
		moc_guispace.cpp \
		moc_mainwindow.cpp \
		qrc_application.cpp
OBJECTS       = bank.o \
		centralwidget.o \
		dialog.o \
		dialogpieces.o \
		guiplayer.o \
		guiplayerhorizontal.o \
		guiplayervertical.o \
		guispace.o \
		mainwindow.o \
		player.o \
		sorry.o \
		space.o \
		moc_centralwidget.o \
		moc_guiplayer.o \
		moc_guiplayerhorizontal.o \
		moc_guiplayervertical.o \
		moc_guispace.o \
		moc_mainwindow.o \
		qrc_application.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sorry.pro
QMAKE_TARGET  = sorry
DESTDIR       = 
TARGET        = sorry

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sorry.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile sorry.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile sorry.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sorry1.0.0 || $(MKDIR) .tmp/sorry1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sorry1.0.0/ && $(COPY_FILE) --parents bank.h centralwidget.h dialog.h dialogpieces.h guiplayer.h guiplayerhorizontal.h guiplayervertical.h guispace.h mainwindow.h player.h space.h .tmp/sorry1.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/sorry1.0.0/ && $(COPY_FILE) --parents bank.cpp centralwidget.cpp dialog.cpp dialogpieces.cpp guiplayer.cpp guiplayerhorizontal.cpp guiplayervertical.cpp guispace.cpp mainwindow.cpp player.cpp sorry.cpp space.cpp .tmp/sorry1.0.0/ && (cd `dirname .tmp/sorry1.0.0` && $(TAR) sorry1.0.0.tar sorry1.0.0 && $(COMPRESS) sorry1.0.0.tar) && $(MOVE) `dirname .tmp/sorry1.0.0`/sorry1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sorry1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_centralwidget.cpp moc_guiplayer.cpp moc_guiplayerhorizontal.cpp moc_guiplayervertical.cpp moc_guispace.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_centralwidget.cpp moc_guiplayer.cpp moc_guiplayerhorizontal.cpp moc_guiplayervertical.cpp moc_guispace.cpp moc_mainwindow.cpp
moc_centralwidget.cpp: guispace.h \
		space.h \
		player.h \
		guiplayer.h \
		centralwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) centralwidget.h -o moc_centralwidget.cpp

moc_guiplayer.cpp: player.h \
		guiplayer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) guiplayer.h -o moc_guiplayer.cpp

moc_guiplayerhorizontal.cpp: player.h \
		guiplayer.h \
		guiplayerhorizontal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) guiplayerhorizontal.h -o moc_guiplayerhorizontal.cpp

moc_guiplayervertical.cpp: player.h \
		guiplayer.h \
		guiplayervertical.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) guiplayervertical.h -o moc_guiplayervertical.cpp

moc_guispace.cpp: space.h \
		player.h \
		guispace.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) guispace.h -o moc_guispace.cpp

moc_mainwindow.cpp: guiplayerhorizontal.h \
		player.h \
		guiplayer.h \
		guiplayervertical.h \
		centralwidget.h \
		guispace.h \
		space.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		images/piece1.png \
		images/piece5.png \
		images/chance1.png \
		images/cardfacedown.png \
		images/piece9.png \
		images/chancedown.jpg \
		images/upgradebutton.png \
		images/dice4.jpg \
		images/communitychest1.png \
		images/piece2.png \
		images/communitydown.jpg \
		images/piece6.png \
		images/chance0.png \
		images/diceupdated.jpg \
		images/dice1.jpg \
		images/communitychest2.png \
		images/dice5.png \
		images/chance3.png \
		images/piece3.png \
		images/piece7.png \
		images/card5.png \
		images/buybutton.png \
		images/communitychest3.png \
		images/dice6.png \
		images/dice2.png \
		images/piece0.png \
		images/chance2.png \
		images/piece4.png \
		images/endbutton.png \
		images/piece8.png \
		images/dice3.jpg \
		images/communitychest0.png
	/usr/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

bank.o: bank.cpp bank.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bank.o bank.cpp

centralwidget.o: centralwidget.cpp centralwidget.h \
		guispace.h \
		space.h \
		player.h \
		guiplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o centralwidget.o centralwidget.cpp

dialog.o: dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

dialogpieces.o: dialogpieces.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogpieces.o dialogpieces.cpp

guiplayer.o: guiplayer.cpp guiplayer.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiplayer.o guiplayer.cpp

guiplayerhorizontal.o: guiplayerhorizontal.cpp guiplayerhorizontal.h \
		player.h \
		guiplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiplayerhorizontal.o guiplayerhorizontal.cpp

guiplayervertical.o: guiplayervertical.cpp guiplayervertical.h \
		player.h \
		guiplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiplayervertical.o guiplayervertical.cpp

guispace.o: guispace.cpp guispace.h \
		space.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guispace.o guispace.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		guiplayerhorizontal.h \
		player.h \
		guiplayer.h \
		guiplayervertical.h \
		centralwidget.h \
		guispace.h \
		space.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

player.o: player.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

sorry.o: sorry.cpp mainwindow.h \
		guiplayerhorizontal.h \
		player.h \
		guiplayer.h \
		guiplayervertical.h \
		centralwidget.h \
		guispace.h \
		space.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sorry.o sorry.cpp

space.o: space.cpp space.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o space.o space.cpp

moc_centralwidget.o: moc_centralwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_centralwidget.o moc_centralwidget.cpp

moc_guiplayer.o: moc_guiplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guiplayer.o moc_guiplayer.cpp

moc_guiplayerhorizontal.o: moc_guiplayerhorizontal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guiplayerhorizontal.o moc_guiplayerhorizontal.cpp

moc_guiplayervertical.o: moc_guiplayervertical.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guiplayervertical.o moc_guiplayervertical.cpp

moc_guispace.o: moc_guispace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guispace.o moc_guispace.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

